---
build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
args:
  CARGO_FEATURES: 'all-engines,vad-silero'
labels:
  io.hass.name: 'Wyoming ASR'
  io.hass.description: 'Multi-engine speech-to-text with Wyoming protocol'
  io.hass.type: addon
  io.hass.version: '0.1.0'
